POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "super_admin_dz",
    "password": "Admin@123456"
}
###  LOGIN AS customer
# Run this first to get the @admin_token
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "customer_test_02",
    "password": "password123"
}



### --- CONFIGURATION & TOKENS ---
@baseUrl = http://localhost:4000
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg1NmM5MDM3OWU0OTc0MzIzOGVkMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2OTY4NDA0NiwiZXhwIjoxNzY5Njg3MzQ2fQ.fGOGwIz_sZtLvFU0tgsWjpaZ8mXu2kwIoM5o4sysAyQ
@customer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg1NmM5MDM3OWU0OTc0MzIzOGVkMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2OTY3OTc2OCwiZXhwIjoxNzcwMjg0NTY4fQ.a97K_hkx8eyGeAnK1SwRsFTEE7bi6itVEvER5CiKRjI
@orderId = 697b08aed7d5aa3c3a04c161
@productId = 697b03f581ca2a08ab418a7c








### 1. Get Totals with Growth (Revenue & Orders)
### Compares last 30 days vs previous 30 days
GET {{baseUrl}}/dashboard/getTotalsWithGrowth
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 2. Get Chart Analytics (Weekly Revenue)
### Options: range=week|year , type=revenue|orders|clients
GET {{baseUrl}}/dashboard/getAnalytics?range=week&type=clients
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 3. Get Chart Analytics (Yearly Client Growth)
GET {{baseUrl}}/dashboard/getAnalytics?range=year&type=clients
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 4. Get Top Products (By Revenue)
### Options: limit=5&type=revenue|quantity
GET {{baseUrl}}/dashboard/getTopProductsAnalytics?limit=20&type=revenue
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 5. Get Top Clients (High Spenders)
### Options: page=1&sortBy=revenue|orders
GET {{baseUrl}}/dashboard/getTopClients?page=1&sortBy=orders
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 6. Get Revenue Report (Tabular Data)
### Options: interval=day|month|year&page=1&limit=10
GET {{baseUrl}}/dashboard/getRevenueReport?interval=day&page=1&limit=10
Authorization: Bearer {{admin_token}}




