
@baseUrl = http://localhost:4000
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg1NmM5MDM3OWU0OTc0MzIzOGVkMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2OTY3MDIxNywiZXhwIjoxNzY5NjczNTE3fQ.Oe4W_uxcCOghc3FaczyVobcgWA6Uz3JS6o3i4yQQmlA
@customer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg2Mzc2MjdhMWYxM2ZmNGEzYWVhMCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc2OTY2MDIzNywiZXhwIjoxNzY5NjYzNTM3fQ.rLTFesZGaaeREMjrI-eDdM-IeWmQCeDtErhDelX2tuI


### -------------------------------------------
### 2. PUBLIC PRODUCT ROUTES (Everyone)
### -------------------------------------------

@productId = 697a18bc305e4f77ec36b7da

### Get All Products (With Search, Sort, and Pagination)
GET {{baseUrl}}/products?sort=title&limit=30&page=1
Authorization: Bearer {{admin_token}}

###

### Get Single Product by ID
GET {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{admin_token}}
Accept: application/json

### -------------------------------------------
### 3. PROTECTED PRODUCT ROUTES (Admin/Manager Only)
### -------------------------------------------

### Create New Product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "title": "aaaa test 24",
    "price": 5500,
    "image": "mouse.jpg",
    "brandID": "697add5559df02f3b6e3673d",
    "units_num": 15
}

###

### Update Product (Partial Update)
PATCH {{baseUrl}}/products/{{productId}}
Content-Type: application/json
Authorization: Bearer {{customer_token}}

{
    "title": "Bnina",
    "price": 4900,
    "units_num": 12,
    "state": "unvailable"
}

###

### Delete Product
DELETE {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{admin_token}}

### -------------------------------------------
### 4. SECURITY / CRACK TESTS
### -------------------------------------------

### Test: Customer trying to delete (Should fail 403)
DELETE {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{customer_token}}