POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "super_admin_dz",
    "password": "Admin@123456"
}
###  LOGIN AS customer
# Run this first to get the @admin_token
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "username": "customer_test_02",
    "password": "password123"
}



### --- CONFIGURATION & TOKENS ---
@baseUrl = http://localhost:4000
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg1NmM5MDM3OWU0OTc0MzIzOGVkMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2OTY4Nzk1MiwiZXhwIjoxNzY5NjkxMjUyfQ.9bHIDGUdW66YnjtqCIjHqcucCEAaKA5nbu4ymVrNtBA
@customer_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Nzg2Mzc2MjdhMWYxM2ZmNGEzYWVhMCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc2OTY4Nzk2MywiZXhwIjoxNzY5NjkxMjYzfQ.ClQ5OSXHWcLsLsHpfaDxOHDzQDoyLQ2b7qZiLJOYi5s



### 1. Create Feedback (As a User)
# Authenticate first to get the token
POST {{baseUrl}}/feedbacks
Content-Type: application/json
Authorization: Bearer {{customer_token}}

{
    "comment": "This is a great product! Highly recommended."
}

### ----------------------------------------------------------

### 2. Get All Feedbacks (Admin Only)
GET {{baseUrl}}/feedbacks?page=1&limit=5
Authorization: Bearer {{admin_token}}

### ----------------------------------------------------------

### 3. Create Feedback - Error Test (Empty Comment)
POST {{baseUrl}}/feedbacks
Content-Type: application/json
Authorization: Bearer {{customer_token}}

{
    "comment": ""
}